jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      test:
        task: test test-all
      spec:
        task: test-spec
      bundled_gems:
        task: test-bundled-gems
      bundler:
        task: test-bundler
  steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: '2.5.1'
  - script: sudo apt update -qy && sudo apt-get build-dep ruby2.3
  - script: |
      autoconf
      ./configure
      make
    displayName: 'make'
  - script: make $(task)
    displayName: "make exam"

- job: macOS
  pool:
    vmImage: 'macos-10.13'
  strategy:
    matrix:
      test:
        task: test test-all
      spec:
        task: test-spec
      bundled_gems:
        task: test-bundled-gems
      bundler:
        task: test-bundler
  steps:
  - script: brew update && brew install autoconf bison openssl
  - script: |
      autoconf
      ./configure --with-openssl-dir=/usr/local/opt/openssl
      make
    displayName: 'make'
  - script: make $(task)
    displayName: "make exam"

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      win32/configure.bat
      nmake
    displayName: 'nmake'
  - script: |
      nmake test
      nmake test-all
      nmake test-spec
    displayName: "nmake exam"
