name: Publish Ruby packages
on:
  push:
    tags:
      - '*'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Set latest flag for Ruby 3.3
        if: contains(github.ref, 'v3_3')
        run: |
          echo "LATEST=true" >> $GITHUB_ENV

      - name: Convert tag name to dot from underscore
        run: |
            # vX_Y_Z to X.Y.Z
            echo "RUBY_VERSION=$(echo ${{ github.ref }} | sed 's/v\([0-9]*\)_\([0-9]*\)_\([0-9]*\)/\1.\2.\3/')" >> $GITHUB_ENV
      - name: Build and push Docker images
        run: |
          curl -L -X POST \
            -H "Authorization: Bearer ${{ secrets.MATZBOT_GITHUB_WORKFLOW_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/ruby/docker-images/dispatches \
            -d '{"event_type": "build", "client_payload": {"ruby_version": "${{ env.RUBY_VERSION }}", "arch": "amd64", "latest": "${{ env.LATEST }}"}}'
